products:
  mug1:
    part1:
      x: 0.060
      y: 0.060
      z: 0.10
    part2: 
      x: 0.03
      y: 0.06
      z: 0.01
    dist:
      x: 0.04
      y: 0.00 
      z: 0.00
  mug2:
    part1:
      x: 0.070
      y: 0.070
      z: 0.080
    part2: 
      x: 0.03
      y: 0.05
      z: 0.012
    dist: 
      x: 0.00
      y: -0.04
      z: 0.00   
  mug3:
    part1:
      x: 0.09
      y: 0.09
      z: 0.1
    part2: 
      x: 0.04
      y: 0.05
      z: 0.01
    dist: 
      x: 0.035
      y: -0.035
      z: 0.00

  bottle1:
    part1:
      x: 0.08
      y: 0.08
      z: 0.23
    part2:
      x: 0.04
      y: 0.04
      z: 0.045
    dist: 
      x: 0.00
      y: 0.00
      z: 0.14
  bottle2:
    part1:
      x: 0.055
      y: 0.055
      z: 0.12
    part2:
      x: 0.03
      y: 0.03
      z: 0.02
    dist: 
      x: 0.00
      y: 0.00
      z: 0.07
  bottle3:
    part1:
      x: 0.05
      y: 0.05
      z: 0.13
    part2:
      x: 0.02
      y: 0.02
      z: 0.02
    dist: 
      x: 0.00
      y: 0.00
      z: 0.075

  glass1:
    part1:
      x: 0.06
      y: 0.06
      z: 0.20
    part2:
      x: 0.02
      y: 0.02
      z: 0.04
    dist: 
      x: 0.00
      y: 0.00
      z: 0.12
  glass2:
    part1:
      x: 0.06
      y: 0.06
      z: 0.08
    part2:
      x: 0.01
      y: 0.01
      z: 0.07
    dist: 
      x: 0.00
      y: 0.00
      z: 0.075
  glass3:
    part1:
      x: 0.05
      y: 0.05
      z: 0.15
    part2:
      x: 0.025
      y: 0.025
      z: 0.03
    dist: 
      x: 0.00
      y: 0.00
      z: 0.09

  ladle1:
    part1:
      x: 0.05
      y: 0.05
      z: 0.04
    part2:
      x: 0.01
      y: 0.02
      z: 0.12
    dist: 
      x: 0.00
      y: 0.08
      z: 0.02
  ladle2:
    part1:
      x: 0.05
      y: 0.02
      z: 0.05
    part2:
      x: 0.02
      y: 0.02
      z: 0.10
    dist: 
      x: 0.00
      y: 0.06
      z: 0.00
  ladle3:
    part1:
      x: 0.04
      y: 0.06
      z: 0.06
    part2:
      x: 0.02
      y: 0.02
      z: 0.15
    dist: 
      x: 0.00
      y: 0.10
      z: 0.03

  hammer1:
    part1:
      x: 0.025
      y: 0.025
      z: 0.16
    part2:
      x: 0.03
      y: 0.05
      z: 0.11
    dist: 
      x: 0.00
      y: 0.13
      z: 0.00
  hammer2:
    part1:
      x: 0.03
      y: 0.04
      z: 0.25
    part2:
      x: 0.03
      y: 0.025
      z: 0.15
    dist: 
      x: 0.00
      y: 0.14
      z: 0.00
  hammer3:
    part1:
      x: 0.025
      y: 0.04
      z: 0.17
    part2:
      x: 0.025
      y: 0.05
      z: 0.012
    dist:
      x: 0.00
      y: 0.10
      z: 0.00

  pan1:
    part1:
      x: 0.02
      y: 0.03
      z: 0.13
    part2:
      x: 0.05
      y: 0.18
      z: 0.20
    dist: 
      x: 0.00
      y: 0.13
      z: 0.01
  pan2:
    part1:
      x: 0.05
      y: 0.23
      z: 0.23
    part2:
      x: 0.02
      y: 0.03
      z: 0.13
    dist:
      x: 0.00
      y: 0.16
      z: 0.03
  pan3:
    part1:
      x: 0.04
      y: 0.17
      z: 0.20
    part2:
      x: 0.015
      y: 0.02
      z: 0.13
    dist: 
      x: 0.12
      y: 0.00
      z: 0.02

  wrench1:
    part1:
      x: 0.015
      y: 0.020
      z: 0.14
    part2:
      x: 0.030
      y: 0.065
      z: 0.075
    dist: 
      x: 0.00
      y: 0.11
      z: 0.00
  wrench2:
    part1:
      x: 0.01
      y: 0.02
      z: 0.17
    part2:
      x: 0.015
      y: 0.05
      z: 0.05
    dist: 
      x: 0.12
      y: 0.00
      z: 0.00
