products:
  mug_01:
    id: 1
    size:
      x: 0.050
      y: 0.070
      z: 0.080
    dist_to_center:
      x: 0.000
      y: 0.000
      z: -0.030
  mug_02:
    id: 2 
    size:
      x: 0.050
      y: 0.070
      z: 0.080
    dist_to_center:
      x: 0.000
      y: 0.000
      z: -0.030
  mug_03:
    id: 3 
    size:
      x: 0.050
      y: 0.070
      z: 0.080
    dist_to_center:
      x: 0.000
      y: 0.000
      z: -0.030
  glass_01:
    id: 4
    size:
      x: 0.050
      y: 0.070
      z: 0.080
    dist_to_center:
      x: 0.000
      y: 0.000
      z: -0.030
  glass_02:
    id: 5 
    size:
      x: 0.050
      y: 0.070
      z: 0.080
    dist_to_center:
      x: 0.000
      y: 0.000
      z: -0.030
  glass_03:
    id: 6 
    size:
      x: 0.050
      y: 0.070
      z: 0.080
    dist_to_center:
      x: 0.000
      y: 0.000
      z: -0.030
  bottle_01:
    id: 7
    size:
      x: 0.050
      y: 0.070
      z: 0.080
    dist_to_center:
      x: 0.000
      y: 0.000
      z: -0.030
  bottle_02:
    id: 8 
    size:
      x: 0.050
      y: 0.070
      z: 0.080
    dist_to_center:
      x: 0.000
      y: 0.000
      z: -0.030
  bottle_03:
    id: 9 
    size:
      x: 0.050
      y: 0.070
      z: 0.080
    dist_to_center:
      x: 0.000
      y: 0.000
      z: -0.030
  fry_pan_01:
    id: 10
    size:
      x: 0.050
      y: 0.070
      z: 0.080
    dist_to_center:
      x: 0.000
      y: 0.000
      z: -0.030
  fry_pan_02:
    id: 11
    size:
      x: 0.050
      y: 0.070
      z: 0.080
    dist_to_center:
      x: 0.000
      y: 0.000
      z: -0.030
  fry_pan_03:
    id: 12
    size:
      x: 0.050
      y: 0.070
      z: 0.080
    dist_to_center:
      x: 0.000
      y: 0.000
      z: -0.030
  hammer_01:
    id: 13 
    size:
      x: 0.050
      y: 0.070
      z: 0.080
    dist_to_center:
      x: 0.000
      y: 0.000
      z: -0.030
  hammer_02:
    id: 14
    size:
      x: 0.050
      y: 0.070
      z: 0.080
    dist_to_center:
      x: 0.000
      y: 0.000
      z: -0.030
  hammer_03:
    id: 15
    size:
      x: 0.050
      y: 0.070
      z: 0.080
    dist_to_center:
      x: 0.000
      y: 0.000
      z: -0.030
  ladle_01:
    id: 16 
    size:
      x: 0.050
      y: 0.070
      z: 0.080
    dist_to_center:
      x: 0.000
      y: 0.000
      z: -0.030
  ladle_02:
    id: 17 
    size:
      x: 0.050
      y: 0.070
      z: 0.080
    dist_to_center:
      x: 0.000
      y: 0.000
      z: -0.030
  ladle_03:
    id: 18 
    size:
      x: 0.050
      y: 0.070
      z: 0.080
    dist_to_center:
      x: 0.000
      y: 0.000
      z: -0.030