hierachical_ems: 
    OutlierRatio: 0.738             # prior outlier probability [0, 1) (default: 0.1)
    MaxIterationEM: 14            # maximum number of EM iterations (default: 20)
    ToleranceEM: 0.00630            # absolute tolerance of EM (default: 1e-3)
    RelativeToleranceEM: 0.928      # relative tolerance of EM (default: 1e-1)
    MaxOptiIterations: 2          # maximum number of optimization iterations per M (default: 2)
    Sigma: 0.3                    # 0.3 initial sigma^2 (default: 0 - auto generate)
    MaxiSwitch: 4                 # maximum number of switches allowed (default: 2)
    AdaptiveUpperBound: True      # Introduce adaptive upper bound to restrict the volume of SQ (default: false)
    Rescale: True                 # normalize the input point cloud (default: true)
    MaxLayer: 3                   # maximum depth
    Eps: 0.0401                     # 0.03 IMPORTANT: varies based on the size of the input pointcoud (DBScan parameter)
    MinPoints: 150                # DBScan parameter required minimum points
    Max_superquadrics: 4          # DBScan parameter required minimum points